Add R11G11B10FloatToBGRA32
AssetRipper/TextureDecoder pull request #17
Opened 2022-11-04 09:33 UTC by yretenai

Known in [Unity as `GraphicsFormat.B10G11R11_UFloatPack32`,](https://github.com/Unity-Technologies/Graphics/blob/5be27c17b2816b7418466aea294aa3b03a59f3b4/Packages/com.unity.render-pipelines.high-definition/Runtime/Lighting/LightCookieManager.cs#L13) usually used for lightmap and HDR data.

- DXGI Type: R11G11B10_FLOAT
- OpenGL Type: GL_R11F_G11F_B10F 

MS Reference code: https://github.com/microsoft/DirectX-Graphics-Samples/blob/e5ea2ac7430ce39e6f6d619fd85ae32581931589/MiniEngine/Core/Shaders/PixelPacking_R11G11B10.hlsli#L31-L37

2022-11-04 15:52 UTC, ds5678 requested changes
A lot to unpack with this, despite the small line count.

- The `RBAConverter.{format name}ToBGRA32` methods are legacy code and scheduled to be removed at some point. This is partially my fault; I should have added obsolete attributes to signal my intent. These methods have been replaced with structs in the `Formats` namespace. Your current method can stay for use in unit tests, ie [RGBTests](https://github.com/AssetRipper/TextureDecoder/blob/master/AssetRipper.TextureDecoder.Tests/RgbTests.cs) and [NewRGBTests](https://github.com/AssetRipper/TextureDecoder/blob/master/AssetRipper.TextureDecoder.Tests/NewRgbTests.cs).
- I'm concerned about the use of `Half` and `float`. Given that the significand for `Half` uses 10 bits not including the sign bit ([reference 1](https://en.wikipedia.org/wiki/Half-precision_floating-point_format), [reference 2](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Half.cs)), this is actually just an integer. The single exponent bit for R and G could only double the significand, the same as normal integer types. It should be more efficient to use `ushort` directly (similar to [RGB16](https://github.com/AssetRipper/TextureDecoder/blob/master/AssetRipper.TextureDecoder/Rgb/Formats/ColorRGB16.cs)). You should verify all this with unit tests and document accordingly. Assuming my thoughts are correct, I want this to be `RGB32 : IColor<ushort>`, otherwise `RGB32Half : IColor<Half>`.
- You should add a line [here](https://github.com/AssetRipper/TextureDecoder/blob/master/AssetRipper.TextureDecoder.TestGenerator/Program.cs#L23-L24) and run automated test generation for the new color struct.

2022-11-05 16:58 UTC, yretenai commented
f16 still has 5 exponent bits, i.e. 0x3401 is 0.2503~ there's no neat conversion to a UNORM value (0x4013 as U16, or 0x3F as U8) without doing what Half does anyway.

2022-11-05 22:22 UTC, ds5678 requested changes
Much closer this time. I would appreciate a test file, but that's not strictly necessary. I verified that this is a format used by Unity, albeit only for render textures.

2022-11-05 22:22 UTC, ds5678 commented on AssetRipper.TextureDecoder/Rgb/Formats/ColorRGB32Half.cs
> +        }
Always use `Unsafe.As` for converting `Half` bits to a `Half` value, and vice versa.

2022-11-05 22:22 UTC, ds5678 commented on AssetRipper.TextureDecoder/Rgb/Formats/ColorRGB32Half.cs
> +        /// 5 bits
This is not 5 bits. A copy paste error I assume. G and B also suffer from this.

2022-11-05 22:22 UTC, ds5678 commented on AssetRipper.TextureDecoder/Rgb/Formats/ColorRGB32Half.cs
> +    /// </summary>
```
/// <remarks>
/// <see href="https://github.com/microsoft/DirectX-Graphics-Samples/blob/e5ea2ac7430ce39e6f6d619fd85ae32581931589/MiniEngine/Core/Shaders/PixelPacking_R11G11B10.hlsli#L31-L37" />
/// </remarks>
```

2022-11-05 22:22 UTC, ds5678 commented on AssetRipper.TextureDecoder.TestGenerator/Program.cs
> +			new GenerationData(typeof(ColorRGB32Half), typeof(Half), 4),
This is causing a merge conflict. You need to rebase.

2022-11-05 22:22 UTC, ds5678 commented on AssetRipper.TextureDecoder.Tests/Formats/ColorRGB32HalfTests.g.cs
> +public partial class ColorRGB32HalfTests
This class is incomplete. Some changes to the source gen were made since your pull request. You'll need to rebase and rerun the source generation.

2022-11-05 22:22 UTC, ds5678 commented on AssetRipper.TextureDecoder.TestGenerator/Program.cs
> +			new GenerationData(typeof(ColorRGB32Half), typeof(Half), 4),
You'll also need to add your new type to the [color source generation](https://github.com/AssetRipper/TextureDecoder/blob/07c653873b8508d0e3e62e40a37284f8e4ca6c11/AssetRipper.TextureDecoder.ColorGenerator/Program.cs#L85).

2022-11-07 03:42 UTC, yretenai commented
Rebased the code and fixed the comments/remarks.

2022-11-07 03:57 UTC, ds5678 requested changes
One small change and then I think this is good, assuming the continuous integration succeeds.

2022-11-07 03:57 UTC, ds5678 commented on AssetRipper.TextureDecoder/Rgb/RgbConverter.cs
> +		public static int R11G11B10FloatToBGRA32(ReadOnlySpan<byte> input, int width, int height, out byte[] output)
I'd like a unit test for this ensuring that the struct exhibits the same behavior.
```cs
//Load one of the other RGB images.
//Convert that data to RGB32Half using the generic conversion method.
//Use this method to convert the compressed data to BGRA32.
//Use the generic conversion method to convert the compressed data to BGRA32.
//Assert equal.
```

2022-11-07 04:10 UTC, yretenai commented
Alright, added the test case using RGB24's sample file. I should probably dump the r11g11b10 texture i was using and provide that but this works too.

2022-11-07 04:11 UTC, ds5678 commented
> I should probably dump the r11g11b10 texture i was using and provide that

If licensing is not an issue, I would greatly appreciate this.

2022-11-07 04:24 UTC, yretenai commented
Unsure on licensing. I'll probably make a new one someday and PR it with the updated test case.

2022-11-07 04:26 UTC, ds5678 commented
Sounds good!

2022-11-07 04:26 UTC, merged

2023-08-02 15:34 UTC, ds5678 commented
@yretenai I think there may be bugs in this color. I had to disable the unit tests for it in the above commit. It is the only color with failing unit tests.

2023-08-02 15:38 UTC, ds5678 commented
If you're not willing to fix the bugs, I would like to remove this color from the codebase, for quality control. This would not impact your ability to use the library. I specifically designed it to be easy for someone to declare their own custom structs inheriting from `IColor<T>`.

2023-08-02 17:55 UTC, yretenai commented
> I specifically designed it to be easy for someone to declare their own custom structs inheriting from IColor<T>.

Feel free to remove it in this case, I'll add it to my own use cases.

2023-08-02 21:29 UTC, ds5678 commented
Thank you for understanding.